language: java
jdk:
  - openjdk11

cache:
  directories:
  - "$HOME/.m2/repository"
  - '$HOME/.gradle'
  
script: "./gradlew clean build"

before_install:
  - chmod +x gradlew  

before_deploy:
  - mkdir -p deploy
  - cp build/libs/*.jar deploy
    
deploy:
  provider: releases
  api_key: $TOKEN
  file: 
    - "deploy/logus-v0.0.1"
    
  file_glob: true
  cleanup: false
  on:
    tags: true
    branch: main
    repo: ijehyunpark/logus
branches:
  only:
    - main
    - /v\d{1,}.\d{1,}.{1,}/